# Generated by Django 5.1 on 2024-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_delete_item_delete_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="read_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
