# Generated by Django 5.1 on 2024-10-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_notification_sender_alter_notification_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="count",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="read_count",
        ),
    ]
