version: '3'


services:
  backend:
    build:
        ./backend/
    ports:
        - 8000:8000
        - 8001:8001

    networks:
        - backend_network
        - db_network
  frontend:
    build:
        ./frontend/
    ports:
        - 3000:3000

    networks:
        - frontend_network

  db: 

  redis:

  nginx:

networks:

volumes:
