
services:
  # backend:
  #   build:
  #       ./backend/
  #   command: uvicorn backend.asgi:application
  #   ports:
  #       - 8000:8000
  
  # frontend: 
  #   build: ./frontend/
  #   command: node ./server/index.mjs
  #   ports:
  #     - 3333:3000
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
