# Generated by Django 5.1 on 2024-10-17 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_room_online_activechat_chatmessage_userstatus_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActiveChat",
            new_name="Chat",
        ),
        migrations.RenameModel(
            old_name="ChatMessage",
            new_name="Message",
        ),
    ]
