# Generated by Django 5.1 on 2024-09-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="post-covers/"),
        ),
    ]
