# Generated by Django 5.1 on 2024-10-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="posts_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
