# Generated by Django 5.1 on 2024-10-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_tag_posts_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="posts_count",
            field=models.IntegerField(default=0),
        ),
    ]
