# Generated by Django 5.1 on 2024-10-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_tag_posts_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["-posts_count"]},
        ),
    ]
