# Generated by Django 5.1 on 2024-09-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_banners/"
            ),
        ),
    ]
