# Generated by Django 5.1 on 2024-09-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_follower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="follower",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="users.profile"
            ),
        ),
    ]
